### ISSUE TITLE
 Error creating source database

### ISSUE THREAD

**Issue by amin9565** [jakirseu/Android-Pre-Built-database#1]
hello 
i download your project and run it but it has stopped !
in first i copy your code in my project with my db and every things was true ... 
but now when run my project and your project both stopped !
i never change any things but stopped !
what do shall ?
very very  thanks

**Comment by jakirseu** [comment]
Check the error log.

**Comment by amin9565** [comment]
`06-30 23:25:27.943 1646-1646/me.jakir.prebuilddatabase E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{me.jakir.prebuilddatabase/me.jakir.prebuilddatabase.MainActivity}: java.lang.RuntimeException: Error creating source database
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2249)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
                                                                             at android.app.ActivityThread.access$700(ActivityThread.java:154)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5306)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: java.lang.RuntimeException: Error creating source database
                                                                             at me.jakir.prebuilddatabase.AssetDatabaseOpenHelper.saveDatabase(AssetDatabaseOpenHelper.java:29)
                                                                             at me.jakir.prebuilddatabase.MainActivity.onCreate(MainActivity.java:24)
                                                                             at android.app.Activity.performCreate(Activity.java:5255)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299) 
                                                                             at android.app.ActivityThread.access$700(ActivityThread.java:154) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                             at android.os.Looper.loop(Looper.java:137) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5306) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                                          Caused by: java.io.FileNotFoundException: /data/data/me.jakir.prebuilddatabase/databases/hello.db: open failed: ENOENT (No such file or directory)
                                                                             at libcore.io.IoBridge.open(IoBridge.java:416)
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:73)
                                                                             at me.jakir.prebuilddatabase.AssetDatabaseOpenHelper.copyDatabase(AssetDatabaseOpenHelper.java:38)
                                                                             at me.jakir.prebuilddatabase.AssetDatabaseOpenHelper.saveDatabase(AssetDatabaseOpenHelper.java:27)
                                                                             at me.jakir.prebuilddatabase.MainActivity.onCreate(MainActivity.java:24) 
                                                                             at android.app.Activity.performCreate(Activity.java:5255) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299) 
                                                                             at android.app.ActivityThread.access$700(ActivityThread.java:154) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                             at android.os.Looper.loop(Looper.java:137) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5306) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                                          Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                             at libcore.io.Posix.open(Native Method)
                                                                             at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
                                                                             at libcore.io.IoBridge.open(IoBridge.java:400)
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:88) 
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:73) 
                                                                             at me.jakir.prebuilddatabase.AssetDatabaseOpenHelper.copyDatabase(AssetDatabaseOpenHelper.java:38) 
                                                                             at me.jakir.prebuilddatabase.AssetDatabaseOpenHelper.saveDatabase(AssetDatabaseOpenHelper.java:27) 
                                                                             at me.jakir.prebuilddatabase.MainActivity.onCreate(MainActivity.java:24) 
                                                                             at android.app.Activity.performCreate(Activity.java:5255) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299) 
                                                                             at android.app.ActivityThread.access$700(ActivityThread.java:154) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                             at android.os.Looper.loop(Looper.java:137) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5306) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                             at dalvik.system.NativeStart.main(Native Method) `
